### ISSUE TITLE
Update folder?

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2-community-edition#11]
What is the update folder for?

**Comment by buskamuza** [comment]
Hi @craigcarnell ,

it is an Updater application used for components management in Setup Wizard (Admin Panel > System > Web Setup Wizard). Updater application is absolutely separate from Magento application and is used for updating the code. If something goes wrong, the user can use this application to rollback to the previous state.

**Comment by craigcarnell** [comment]
@buskamuza OK Thanks. From my perspective it just looked like an older version.

Is there anyway while using this to fetch down the latest magento2 develop? Or am I stuck with composer using the latest tagged release? Thanks

**Comment by alankent** [comment]
We have an RC coming "Real Soon Now" which might be useful - but I don't have precise details what will and will not be in the RC yet.
