### ISSUE TITLE
Redirect Loop error on admin directory after fresh install

### ISSUE THREAD

**Issue by LucaTerzaghi** [magento/magento2-community-edition#13]

**Comment by LucaTerzaghi** [comment]
URL http://localhost:8888/admin/admin/index/index/key/64cc7fe2b745fe7db10b4f2916e19cf3aa928fd1893cb129aa445544a66cf7fe/

**Comment by buskamuza** [comment]
Hi, @LucaTerzaghi .
Do you have the same issue, if you use a hostname with dots? Like "magdento.loc" or something like that? Some browsers work badly with cookies for "localhost" domain.

**Comment by LucaTerzaghi** [comment]
Trying with http://magento.local ! PS i am using Entreprise Edition latest version.

**Comment by LucaTerzaghi** [comment]
Working! :) Thanks!

**Comment by simvegas** [comment]
I am actually getting this issue with a version installed on Amazon AWS. The bugs...they're everywhere!!
